[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = ["pytest", "ruff"]

[project]
name = "alr"
version = "0.0.1"
description = "A tool for running ralph loops"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "PyYAML>=6",
    "pydantic>=2",
]

[project.scripts]
alr = "alr.main:main"

[tool.ruff.lint]
select = ["N"]